# docker-compose.yml

version: "3.0"                 # docker compose 파일의 버전

services: # 아래는 서비스 정의  
   frontapp:                   # service1의 명칭  
      # 서비스 빌드를 위한 정의 내용
      build: ./FrontEnd/app 
      image: ${DOCKER_USR}/frontapp
      ports: 
         - "80:80"

   backapp:                   # service2의 명칭  
      # 서비스 빌드를 위한 정의 내용
      build: ./BackEnd
      image: ${DOCKER_USR}/backapp
      ports:
      - "8080:8080"
